### ISSUE TITLE
Looking for svelte/store.mjs

### ISSUE THREAD

**Issue by niczero** [EricPKerr/sapper-tailwindcss#1]
I checked out master (fc43215) and did `npm ci` then `npm run build` -- both completed without problem.  But when I do `npm run start` I get
```
> sapper-tailwindcss@0.0.1 start /home/nsandfield/proj/svelte/x/sapper-tailwindcss
> node __sapper__/build

Starting server on port 3000
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'svelte/store.mjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nsandfield/proj/svelte/x/sapper-tailwindcss/__sapper__/build/server/server.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sapper-tailwindcss@0.0.1 start: `node __sapper__/build`
npm ERR! Exit status 1
```

Now, I do have `node_modules/svelte/store/index.mjs` so maybe there's a version problem, but I thought `ci` would avoid that.

This commit updated some dependencies, so I tried the previous commit (1d362eb) but resulting messages are identical.

**Comment by EricPKerr** [comment]
@niczero package.json was referencing `0.27` instead of `0.27.4` for sapper.  Upgraded and it's fixed now.  Thanks
